# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'photo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(807, 603)
        MainWindow.setStyleSheet("background-color: #3C3B3A;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 90, 561, 321))
        self.label.setStyleSheet("background-color:white;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(30, 70, 111, 451))
        self.listWidget.setStyleSheet("background-color:white;")
        self.listWidget.setObjectName("listWidget")
        self.btn_left = QtWidgets.QPushButton(self.centralwidget)
        self.btn_left.setGeometry(QtCore.QRect(160, 480, 101, 41))
        self.btn_left.setStyleSheet("background-color:#FFB621;\n"
"border-radius:10px;\n"
"font-weight: bold;")
        self.btn_left.setObjectName("btn_left")
        self.btn_right = QtWidgets.QPushButton(self.centralwidget)
        self.btn_right.setGeometry(QtCore.QRect(290, 480, 101, 41))
        self.btn_right.setStyleSheet("background-color:#FFB621;\n"
"border-radius:10px;\n"
"font-weight: bold;")
        self.btn_right.setObjectName("btn_right")
        self.btn_flip = QtWidgets.QPushButton(self.centralwidget)
        self.btn_flip.setGeometry(QtCore.QRect(420, 480, 101, 41))
        self.btn_flip.setStyleSheet("background-color:#FFB621;\n"
"border-radius:10px;\n"
"font-weight: bold;")
        self.btn_flip.setObjectName("btn_flip")
        self.btn_bw = QtWidgets.QPushButton(self.centralwidget)
        self.btn_bw.setGeometry(QtCore.QRect(680, 480, 101, 41))
        self.btn_bw.setStyleSheet("background-color:#FFB621;\n"
"border-radius:10px;\n"
"font-weight: bold;")
        self.btn_bw.setObjectName("btn_bw")
        self.btn_dir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dir.setGeometry(QtCore.QRect(40, 20, 91, 31))
        self.btn_dir.setStyleSheet("background-color:#FFB621;\n"
"border-radius:10px;\n"
"font-weight: bold;")
        self.btn_dir.setObjectName("btn_dir")
        self.btn_sharp = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sharp.setGeometry(QtCore.QRect(550, 480, 101, 41))
        self.btn_sharp.setStyleSheet("background-color:#FFB621;\n"
"border-radius:10px;\n"
"font-weight: bold;")
        self.btn_sharp.setObjectName("btn_sharp")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(670, 540, 104, 13))
        self.label_2.setStyleSheet("color:white;")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_left.setText(_translate("MainWindow", "Вліво"))
        self.btn_right.setText(_translate("MainWindow", "Вправо"))
        self.btn_flip.setText(_translate("MainWindow", "Дзеркально"))
        self.btn_bw.setText(_translate("MainWindow", "Ч/Б"))
        self.btn_dir.setText(_translate("MainWindow", "Папка"))
        self.btn_sharp.setText(_translate("MainWindow", "Різкість"))
        self.label_2.setText(_translate("MainWindow", "Made by Mark @2024"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
