# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'smart_notes.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(975, 729)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 30, 561, 631))
        self.textEdit_2.setStyleSheet("border: 5px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"text-decoration: none;\n"
"color: black;\n"
"background: white;\n"
"box-shadow: 0 5px 0 #003CC5;\n"
"")
        self.textEdit_2.setObjectName("textEdit_2")
        self.list_1 = QtWidgets.QListWidget(self.centralwidget)
        self.list_1.setGeometry(QtCore.QRect(590, 60, 331, 161))
        self.list_1.setStyleSheet("border: 5px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"text-decoration: none;\n"
"color: black;\n"
"background: white;\n"
"box-shadow: 0 5px 0 #003CC5;\n"
"")
        self.list_1.setObjectName("list_1")
        self.list_2 = QtWidgets.QListWidget(self.centralwidget)
        self.list_2.setGeometry(QtCore.QRect(600, 360, 331, 161))
        self.list_2.setStyleSheet("border: 5px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"text-decoration: none;\n"
"color: black;\n"
"background: white;\n"
"box-shadow: 0 5px 0 #003CC5;\n"
"")
        self.list_2.setObjectName("list_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(590, 30, 331, 31))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(600, 540, 331, 22))
        self.lineEdit.setStyleSheet("border: 5px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 3px;\n"
"text-decoration: none;\n"
"color: black;\n"
"background: white;\n"
"box-shadow: 0 5px 0 #003CC5;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.btn_make = QtWidgets.QPushButton(self.centralwidget)
        self.btn_make.setGeometry(QtCore.QRect(600, 240, 141, 31))
        self.btn_make.setStyleSheet("border: none;\n"
"    border-radius: 10px;\n"
"    text-decoration: none;\n"
"    color: white;\n"
"    background: #0B63F6;\n"
"    box-shadow: 0 5px 0 #003CC5;\n"
"")
        self.btn_make.setObjectName("btn_make")
        self.btn_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete.setGeometry(QtCore.QRect(770, 240, 151, 31))
        self.btn_delete.setStyleSheet("border: none;\n"
"    border-radius: 10px;\n"
"    text-decoration: none;\n"
"    color: white;\n"
"    background: #0B63F6;\n"
"    box-shadow: 0 5px 0 #003CC5;")
        self.btn_delete.setObjectName("btn_delete")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(600, 290, 321, 31))
        self.btn_save.setStyleSheet("border: none;\n"
"    border-radius: 10px;\n"
"    text-decoration: none;\n"
"    color: white;\n"
"    background: #0B63F6;\n"
"    box-shadow: 0 5px 0 #003CC5;")
        self.btn_save.setObjectName("btn_save")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(600, 570, 141, 31))
        self.btn_add.setStyleSheet("border: none;\n"
"    border-radius: 10px;\n"
"    text-decoration: none;\n"
"    color: white;\n"
"    background: #0B63F6;\n"
"    box-shadow: 0 5px 0 #003CC5;")
        self.btn_add.setObjectName("btn_add")
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search.setGeometry(QtCore.QRect(600, 610, 321, 31))
        self.btn_search.setStyleSheet("border: none;\n"
"    border-radius: 10px;\n"
"    text-decoration: none;\n"
"    color: white;\n"
"    background: #0B63F6;\n"
"    box-shadow: 0 5px 0 #003CC5;")
        self.btn_search.setObjectName("btn_search")
        self.btn_detach = QtWidgets.QPushButton(self.centralwidget)
        self.btn_detach.setGeometry(QtCore.QRect(770, 570, 151, 31))
        self.btn_detach.setStyleSheet("border: none;\n"
"    border-radius: 10px;\n"
"    text-decoration: none;\n"
"    color: white;\n"
"    background: #0B63F6;\n"
"    box-shadow: 0 5px 0 #003CC5;")
        self.btn_detach.setObjectName("btn_detach")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(600, 330, 311, 31))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(870, 10, 41, 41))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("notes/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 975, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Список заміток"))
        self.lineEdit.setText(_translate("MainWindow", "Введіть тег..."))
        self.btn_make.setText(_translate("MainWindow", "Створити замітку"))
        self.btn_delete.setText(_translate("MainWindow", "Видалити замітку"))
        self.btn_save.setText(_translate("MainWindow", "Зберегти замітку"))
        self.btn_add.setText(_translate("MainWindow", "Додати до замітки"))
        self.btn_search.setText(_translate("MainWindow", "Шукати замітки по тегу"))
        self.btn_detach.setText(_translate("MainWindow", "Відкріпити від замітки"))
        self.label_2.setText(_translate("MainWindow", "Список тегів"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
